# Generated by Django 3.0.8 on 2020-07-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_part', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_Post_Img',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
